# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new2_calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(873, 557)
        self.result = QtWidgets.QLabel(Dialog)
        self.result.setGeometry(QtCore.QRect(170, 20, 521, 71))
        self.result.setStyleSheet("font: 75 16pt \"Arial\";\n"
"color: rgb(170, 0, 0);")
        self.result.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.result.setObjectName("result")
        self.inputNum1 = QtWidgets.QLineEdit(Dialog)
        self.inputNum1.setGeometry(QtCore.QRect(210, 120, 191, 41))
        self.inputNum1.setObjectName("inputNum1")
        self.inputNum2 = QtWidgets.QLineEdit(Dialog)
        self.inputNum2.setGeometry(QtCore.QRect(480, 120, 201, 41))
        self.inputNum2.setObjectName("inputNum2")
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(240, 180, 151, 41))
        self.addButton.setStyleSheet("font: 12pt \"Arial\";")
        self.addButton.setObjectName("addButton")
        self.pic = QtWidgets.QLabel(Dialog)
        self.pic.setGeometry(QtCore.QRect(10, 10, 91, 91))
        self.pic.setText("")
        self.pic.setPixmap(QtGui.QPixmap("monkey.png"))
        self.pic.setScaledContents(True)
        self.pic.setObjectName("pic")
        self.radioButton_1 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_1.setGeometry(QtCore.QRect(30, 180, 161, 41))
        self.radioButton_1.setStyleSheet("font: 75 12pt \"Arial\";\n"
"color: rgb(0, 44, 134);")
        self.radioButton_1.setAutoExclusive(False)
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setGeometry(QtCore.QRect(30, 240, 151, 31))
        self.radioButton_2.setStyleSheet("font: 75 12pt \"Arial\";\n"
"color: rgb(0, 44, 134);")
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_3.setGeometry(QtCore.QRect(30, 290, 141, 31))
        self.radioButton_3.setStyleSheet("font: 75 12pt \"Arial\";\n"
"color: rgb(5, 145, 5);")
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_4.setGeometry(QtCore.QRect(30, 340, 131, 31))
        self.radioButton_4.setStyleSheet("font: 75 12pt \"Arial\";\n"
"color: rgb(5, 145, 5);")
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.clickMeButton = QtWidgets.QPushButton(Dialog)
        self.clickMeButton.setGeometry(QtCore.QRect(230, 240, 181, 41))
        self.clickMeButton.setStyleSheet("color: rgb(233, 255, 253); font: 75 14pt \"Arial\";\n"
"background-color: rgb(4, 97, 102);")
        self.clickMeButton.setObjectName("clickMeButton")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(250, 300, 141, 61))
        self.checkBox.setStyleSheet("font: 75 12pt \"Arial\";\n"
"color: rgb(105, 0, 158);")
        self.checkBox.setObjectName("checkBox")
        self.animalComboBox = QtWidgets.QComboBox(Dialog)
        self.animalComboBox.setGeometry(QtCore.QRect(500, 240, 161, 41))
        self.animalComboBox.setStyleSheet("background-color: rgb(230, 255, 249);")
        self.animalComboBox.setObjectName("animalComboBox")
        self.comboButton = QtWidgets.QPushButton(Dialog)
        self.comboButton.setGeometry(QtCore.QRect(500, 180, 161, 41))
        self.comboButton.setStyleSheet("font: 75 10pt \"Arial\"; color: rgb(0, 84, 126);\n"
"background-color: rgb(170, 255, 255);")
        self.comboButton.setObjectName("comboButton")
        self.languageComboBox = QtWidgets.QComboBox(Dialog)
        self.languageComboBox.setGeometry(QtCore.QRect(560, 320, 141, 41))
        self.languageComboBox.setStyleSheet("background-color: rgb(78, 90, 113);")
        self.languageComboBox.setObjectName("languageComboBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(460, 330, 81, 21))
        self.label.setStyleSheet("font: 10pt \"Arial\";")
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(40, 430, 271, 31))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalSlider = QtWidgets.QSlider(Dialog)
        self.horizontalSlider.setGeometry(QtCore.QRect(40, 490, 231, 31))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalSlider = QtWidgets.QSlider(Dialog)
        self.verticalSlider.setGeometry(QtCore.QRect(790, 30, 31, 491))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.progressBar4vertical = QtWidgets.QProgressBar(Dialog)
        self.progressBar4vertical.setGeometry(QtCore.QRect(500, 480, 241, 31))
        self.progressBar4vertical.setProperty("value", 24)
        self.progressBar4vertical.setObjectName("progressBar4vertical")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "計算機兒"))
        self.result.setText(_translate("Dialog", "Calculator"))
        self.addButton.setText(_translate("Dialog", "Add"))
        self.radioButton_1.setText(_translate("Dialog", "Radio1 (+)"))
        self.radioButton_2.setText(_translate("Dialog", "Radio2 (-)"))
        self.radioButton_3.setText(_translate("Dialog", "Radio3 (×)"))
        self.radioButton_4.setText(_translate("Dialog", "Radio4 (÷)"))
        self.clickMeButton.setText(_translate("Dialog", "Click me~~"))
        self.checkBox.setText(_translate("Dialog", "CheckBox"))
        self.comboButton.setText(_translate("Dialog", "Show combo box"))
        self.label.setText(_translate("Dialog", "Language: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
